/**:
  ros__parameters:
    thumb_joint_1:
      p: 50.0
      i: 0.0
      d: 2.0
      i_clamp_max: 1.0
      i_clamp_min: -1.0

    thumb_joint_2:
      p: 40.0
      i: 0.0
      d: 1.5
      i_clamp_max: 1.0
      i_clamp_min: -1.0