# Default initial positions for omnihand's ros2_control fake system

initial_positions:
  L_index_abad_joint: 0
  L_index_pip_joint: 0
  L_middle_pip_joint: 0
  L_pinky_abad_joint: 0
  L_pinky_pip_joint: 0
  L_ring_abad_joint: 0
  L_ring_pip_joint: 0
  L_thumb_abad_joint: 0
  L_thumb_mcp_joint: 0
  L_thumb_roll_joint: 0